### ISSUE TITLE
Errors are not accessible since they are private with a lower case

### ISSUE THREAD

**Issue by d4z3x** [bodgit/sevenzip#130]
Shoulnd't the the errors defined in sevenzip be accessible for comparison? Currently, errors are defined with leading lower case, therefore, parking them private to external modules. archive/zip uses "ErrFormat", but this module uses "errFormat."

Can we fix this please?

**Comment by bodgit** [comment]
There's a bunch of errors that can be returned aside from `[eE]rrFormat` and I don't want to have to export them all because they then have to be maintained. Checking with `err != nil` should be sufficient. 

However, I have just merged #278 which wraps most read-type errors which primarily is useful for ascertaining if some sort of encryption was involved, for the purposes of handling wrong passwords.
