### ISSUE TITLE
TODO idEmptyStream

### ISSUE THREAD

**Issue by 89z** [bodgit/sevenzip#4]
Using this file:

https://github.com/89z/visage/releases/download/1.0.0/vs_BuildTools.7z

Running this returns no error or warning:

~~~
7z l vs_BuildTools.7z
~~~

but this program:

~~~go
package main

import (
   "github.com/bodgit/sevenzip"
   "log"
)

func main() {
   r, e := sevenzip.OpenReader("vs_BuildTools.7z")
   if e != nil {
      log.Fatal(e)
   }
   println(r)
}
~~~

I get this result:

~~~
2021/01/19 10:12:53 1 error occurred:
        * sevenzip: TODO idEmptyStream
~~~

**Comment by bodgit** [comment]
Thanks for the bug report.

Do you have a way to generate an archive with this property in it so I can create a small test case archive?

In the meantime I'll use your test case as an example, but I notice it's using the BCJ2 compression method which I don't currently support either, partly because there's no high level docs or code examples on how it works so I haven't been able to create a Go implementation of it yet.

**Comment by 89z** [comment]
So the source is actually this:

https://download.visualstudio.microsoft.com/download/pr/3a7354bc-d2e4-430f-92d0-9abd031b5ee5/1792a192788dbe8af64739f06e62db3317cee536b5f4e04a0eb4b5ca7f58ca78/vs_BuildTools.exe

and the 7z that I linked, is actually embedded in that file. I know that is not
ideal, but it does appear to be a valid 7z file once extracted.

**Comment by bodgit** [comment]
Ok, I was hoping I could create an archive with that property, committing that build tools archive is probably overkill but I'll use that as an example regardless.

There's a handful of properties in 7-zip files that I haven't implemented, mostly because I can't see how to create them in an archive and the docs aren't super clear on their structure and they don't appear in any archive files that I've encountered to date.

I hadn't seen that code, thanks for the link. I will see if I can use that to help understand how it works.

I did search to see if anyone had created a pure Go 7-zip reader before writing this and that project didn't turn up; I found quite a few that were just CGo bindings to the C library which I wanted to avoid as it makes cross-compilation difficult.

**Comment by 89z** [comment]
If it helps, I tested the same file with the below program, and it works as expected:

~~~go
package main

import (
   "github.com/saracen/go7z"
   "io"
   "log"
   "os"
   "path"
)

func main() {
   sz, e := go7z.OpenReader("vs_BuildTools.7z")
   if e != nil {
      log.Fatal(e)
   }
   for {
      hdr, e := sz.Next()
      if e == io.EOF {
         break
      }
      if hdr.IsEmptyStream && ! hdr.IsEmptyFile {
         continue
      }
      os.MkdirAll(path.Dir(hdr.Name), os.ModePerm)
      f, e := os.Create(hdr.Name)
      if e != nil {
         log.Fatal(e)
      }
      io.Copy(f, sz)
   }
}
~~~

**Comment by bodgit** [comment]
So this should now be fixed in the sense that the `OpenReader()` function works now with your test archive. If you try and extract any of the files that use the BCJ2 algorithm then it will produce a different error. I've opened #6 to track that.

**Comment by 89z** [comment]
Isnt that all the files? Or do they use different algorithms?

**Comment by bodgit** [comment]
A 7-zip archive can use different algorithms for certain sets of files; BCJ2 is generally used for compressing Intel executable code. The archive you attached is mostly Windows .dll files so it makes sense for them to use BCJ2 but rather than compress the .html and .json files in there with something else they've also been compressed in the same stream.

**Comment by 89z** [comment]
I dont think this was a Microsoft action (them being the ones who distributed the original file). If I extract everything and make a new archive using 7-Zip, I get the same BCJ2 error.

**Comment by bodgit** [comment]
I think there are some heuristics in play if you just create an archive from all of the files in one go; I suspect if `7za` spots any Intel code in the files then it turns on BCJ2.

Interestingly, I tried the same, I extracted everything and then created a new archive. For me, it added all of the .html and .json files using LZMA2 and then all of the .dll & .exe files using BCJ & LZMA2. This was with version 16.02 of `7za`.

You can also run the `7za` utility in multiple runs to add one set of files with a particular algorithm, then run it again to add some more files to the same archive with a different algorithm, i.e. something like:
```
7za a -m0=lzma test.7z file1 file2 file3
7za a -m0=bzip2 test.7z file4 file5 file6
```
The first three files are compressed with LZMA, the second three are compressed with Bzip2 but they're all part of the same archive. You can confirm it by using `7za l -slt test.7z` and it tells you how each file has been compressed. I think you can override the algorithm when creating the archive but obviously I need to see if I can make BCJ2 work.

**Comment by 89z** [comment]
I am using this:

https://github.com/mcmilk/7-Zip-zstd

So make sense we get different result. At any rate, dont matter what our version do, only matter whats in the file in question. So I will wait until BCJ2 is implemented. Unless you want a pull request?
